name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install SDKMAN!
      run: |
        curl -s "https://get.sdkman.io?rcupdate=false" | bash
        echo "source $HOME/.sdkman/bin/sdkman-init.sh" > $HOME/.bash_env
        echo "BASH_ENV=$HOME/.bash_env" >> $GITHUB_ENV

    - name: Install Java and build with Maven
      run: |
        sdk env install
        mvn clean install
