name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Java
      uses: sdkman/sdkman-action@v1

    - name: Build with Maven
      run: mvn clean install
